export interface ThemePreset {
    name: string;
    mode: 'light' | 'dark';
    primaryColor: string;
    secondaryColor: string;
    accentColor: string;
    backgroundColor: string;
    textColor: string;
    surfaceColor: string;
    borderColor: string;
    mutedColor: string;
    headingColor: string;
}

export interface IGetThemePresetsUseCase {
    execute(): Promise<ThemePreset[]>;
}

export class GetThemePresetsUseCase implements IGetThemePresetsUseCase {
    async execute(): Promise<ThemePreset[]> {
        return [
            
            {
                name: 'Clean Professional',
                mode: 'light',
                primaryColor: '#16a34a',
                secondaryColor: '#1f2937',
                accentColor: '#e5e7eb',
                backgroundColor: '#f7faf9',
                textColor: '#1f2937',
                surfaceColor: '#ffffff',
                borderColor: '#e5e7eb',
                mutedColor: '#6b7280',
                headingColor: '#0f172a',
            },
            
            {
                name: 'Ocean Blue',
                mode: 'light',
                primaryColor: '#3B82F6',
                secondaryColor: '#1e40af',
                accentColor: '#93c5fd',
                backgroundColor: '#eff6ff',
                textColor: '#1e3a8a',
                surfaceColor: '#ffffff',
                borderColor: '#bfdbfe',
                mutedColor: '#64748b',
                headingColor: '#1e3a8a',
            },
            {
                name: 'Forest Green',
                mode: 'light',
                primaryColor: '#10B981',
                secondaryColor: '#047857',
                accentColor: '#6ee7b7',
                backgroundColor: '#ecfdf5',
                textColor: '#065f46',
                surfaceColor: '#ffffff',
                borderColor: '#a7f3d0',
                mutedColor: '#6b7280',
                headingColor: '#064e3b',
            },
            {
                name: 'Royal Purple',
                mode: 'light',
                primaryColor: '#8B5CF6',
                secondaryColor: '#6d28d9',
                accentColor: '#c4b5fd',
                backgroundColor: '#f5f3ff',
                textColor: '#5b21b6',
                surfaceColor: '#ffffff',
                borderColor: '#ddd6fe',
                mutedColor: '#6b7280',
                headingColor: '#4c1d95',
            },
            {
                name: 'Sunset Orange',
                mode: 'light',
                primaryColor: '#F97316',
                secondaryColor: '#c2410c',
                accentColor: '#fdba74',
                backgroundColor: '#fff7ed',
                textColor: '#9a3412',
                surfaceColor: '#ffffff',
                borderColor: '#fed7aa',
                mutedColor: '#6b7280',
                headingColor: '#7c2d12',
            },
            {
                name: 'Rose Pink',
                mode: 'light',
                primaryColor: '#EC4899',
                secondaryColor: '#be185d',
                accentColor: '#f9a8d4',
                backgroundColor: '#fdf2f8',
                textColor: '#9f1239',
                surfaceColor: '#ffffff',
                borderColor: '#fbcfe8',
                mutedColor: '#6b7280',
                headingColor: '#831843',
            },
            {
                name: 'Crimson Red',
                mode: 'light',
                primaryColor: '#EF4444',
                secondaryColor: '#b91c1c',
                accentColor: '#fca5a5',
                backgroundColor: '#fef2f2',
                textColor: '#991b1b',
                surfaceColor: '#ffffff',
                borderColor: '#fecaca',
                mutedColor: '#6b7280',
                headingColor: '#7f1d1d',
            },
            {
                name: 'Teal Wave',
                mode: 'light',
                primaryColor: '#14B8A6',
                secondaryColor: '#0f766e',
                accentColor: '#5eead4',
                backgroundColor: '#f0fdfa',
                textColor: '#115e59',
                surfaceColor: '#ffffff',
                borderColor: '#99f6e4',
                mutedColor: '#6b7280',
                headingColor: '#134e4a',
            },
            {
                name: 'Indigo Night',
                mode: 'light',
                primaryColor: '#6366F1',
                secondaryColor: '#4338ca',
                accentColor: '#a5b4fc',
                backgroundColor: '#eef2ff',
                textColor: '#3730a3',
                surfaceColor: '#ffffff',
                borderColor: '#c7d2fe',
                mutedColor: '#6b7280',
                headingColor: '#312e81',
            },
            {
                name: 'Amber Gold',
                mode: 'light',
                primaryColor: '#F59E0B',
                secondaryColor: '#b45309',
                accentColor: '#fcd34d',
                backgroundColor: '#fffbeb',
                textColor: '#92400e',
                surfaceColor: '#ffffff',
                borderColor: '#fde68a',
                mutedColor: '#6b7280',
                headingColor: '#78350f',
            },
            
            {
                name: 'Midnight Dark',
                mode: 'dark',
                primaryColor: '#60A5FA',
                secondaryColor: '#93c5fd',
                accentColor: '#3b82f6',
                backgroundColor: '#0f172a',
                textColor: '#e2e8f0',
                surfaceColor: '#1e293b',
                borderColor: '#334155',
                mutedColor: '#94a3b8',
                headingColor: '#f1f5f9',
            },
            {
                name: 'Emerald Dark',
                mode: 'dark',
                primaryColor: '#34D399',
                secondaryColor: '#6ee7b7',
                accentColor: '#10b981',
                backgroundColor: '#064e3b',
                textColor: '#d1fae5',
                surfaceColor: '#065f46',
                borderColor: '#047857',
                mutedColor: '#a7f3d0',
                headingColor: '#ecfdf5',
            },
            {
                name: 'Purple Haze Dark',
                mode: 'dark',
                primaryColor: '#A78BFA',
                secondaryColor: '#c4b5fd',
                accentColor: '#8b5cf6',
                backgroundColor: '#1e1b4b',
                textColor: '#e0e7ff',
                surfaceColor: '#312e81',
                borderColor: '#4c1d95',
                mutedColor: '#a5b4fc',
                headingColor: '#eef2ff',
            },
            {
                name: 'Sunset Dark',
                mode: 'dark',
                primaryColor: '#FB923C',
                secondaryColor: '#fdba74',
                accentColor: '#f97316',
                backgroundColor: '#431407',
                textColor: '#fed7aa',
                surfaceColor: '#7c2d12',
                borderColor: '#9a3412',
                mutedColor: '#fde68a',
                headingColor: '#fff7ed',
            },
            {
                name: 'Slate Dark',
                mode: 'dark',
                primaryColor: '#64748B',
                secondaryColor: '#94a3b8',
                accentColor: '#475569',
                backgroundColor: '#020617',
                textColor: '#e2e8f0',
                surfaceColor: '#0f172a',
                borderColor: '#1e293b',
                mutedColor: '#cbd5e1',
                headingColor: '#f8fafc',
            },
        ];
    }
}
