import { UserRole, MenuItem } from "./types";

export const roleMenus: Record<UserRole, MenuItem[]> = {
  superAdmin: [
    { label: "Dashboard", path: "/dashboard" },
    { label: "Companies", path: "/companies" },
    { label: "Plans", path: "/plans" },
    { label: "Purchased Company", path: "/purchased-comapny" },
    { label: "Messages", path: "/message" },
    { label: "Payments", path: "/payments" },
    { label: "Notification", path: "/notification" },
  ],
  company: [  
    { label: "Dashboard", path: "/dashboard" },
    { label: "Departments", path: "/department" },
    { label: "Projects", path: "/projects" },
    { label: "My Team", path: "/team" },
    { label: "Leave Management", path: "/leave" },
    { label: "Meetings", path: "/meetings" },
    { label: "Message", path: "/chat" },
    { label: "Notification", path: "/notification" },
    { label: "Subscription", path: "/subscription" },
    { label: "My Profile", path: "/my-profile" },
  ],
  manager: [ 
    { label: "Dashboard", path: "/dashboard" }, 
    { label: "My Team", path: "/team" },
    { label: "Projects", path: "/projects" },
    { label: "Meetings", path: "/meetings" },
    { label: "Leave Status", path: "/leave-status" },
    { label: "Message", path: "/chat" },
    { label: "Department", path: "/department" },
    { label: "Attendance", path: "/attendance" },
    { label: "Notification", path: "/notification" },
    { label: "My Profile", path: "/profile" },
  ],
  employee: [  
    { label: "Dashboard", path: "/dashboard" },
    { label: "My Tasks", path: "/my-tasks" },
    { label: "Attendance", path: "/attendance" },
    { label: "Leave Status", path: "/leave-status" },
    { label: "Meetings", path: "/meetings" },
    { label: "Message", path: "/message" },
    { label: "Notification", path: "/notification" },
    { label: "My Profile", path: "/my-profile" },
  ],
  general: [
    { label: "Dashboard", path: "/dashboard" },
  ],
};
