name: Backend CI + CD (Dev)

on:
  push:
    branches: [ dev ]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run ESLint
        run: |
          cd backend
          npm run lint

      - name: TypeScript check
        run: |
          cd backend
          npx tsc --noEmit

      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/Stratify
            git pull origin dev
            cd backend
            npm install
            npm run build
            pm2 restart stratify-backend
